name: MultiCraft
main: com.multicraft.MultiCraft
version: 1.0 (alpha)
commands:
  mbuild:
    description: MultiCraft Build Command (From Player Position)
    usage: /<command> x-coord(int) y-coord(int) z-coord(int) material-code(int) hollow-flag(int)
  pyramid:
    description: Build a Square pyramid
    usage: /<command> size(int) material-code(int) hollow-flag(int)
  ray:
    description: Trace a ray for now
    usage: /<command>
  mundo:
    description: MultiCraft Undo Command
    usage: /<command>
  mredo:
    description: MultiCraft Redo Command
    usage: /<command>
  mmbuild:
    description: MultiCraft Build Command (From Cursor Position)
    usage: /<command> z-coord(int) y-coord(int) x-coord(int) material-code(int) hollow-flag(int)
  rbuild:
    description: Initiates a region build
    usage: /<command>
  loc1:
    description: Marks the first location in the selection of a region
    usage: /<command>
  loc2:
    description: Marks the second location in the selection of a region
    usage: /<command>
  rrbuild:
    description: Builds a structure from loc1 to loc2 (Currently solid and made of stone)
    usage: /<command>
  mstore:
    description: Stores a structure's first corner block and opposite corner block by it's given name.
    usage: /<command> name(string) x1-coord(int) y1-coord(int) z1-coord(int) x2-coord(int) y2-coord(int) z2-coord(int)
  mclone:
    description: Uses the Minecraft command clone by applying the first corner block and opposite corner block that was
    saved by mstore.
    usage: /<command> name(string) x-coord(int) y-coord(int) z-coord(int)