name: MultiCraft
main: com.multicraft.MultiCraft
version: 1.0 (alpha)
commands:
  mbuild:
    description: (MultiCraft) build a structure to player position
    usage: /<command> x(int) y(int) z(int) material(int) hollow(int)
  pyramid:
    description: (MultiCraft) build a square pyramid to player position
    usage: /<command> size(int) material(int) hollow(int)
  ray:
    description: (MultiCraft) trace a ray of stone from player line of sight
    usage: /<command>
  mundo:
    description: (MultiCraft) undo command
    usage: /<command>
  mredo:
    description: (MultiCraft) redo command
    usage: /<command>
  mmbuild:
    description: (MultiCraft) build a structure to cursor position
    usage: /<command> x(int) y(int) z(int) material(int) hollow(int)
  rbuild:
    description: (MultiCraft) initiates a region build
    usage: /<command>
  rloc1:
    description: (MultiCraft) marks the first location in the selection of a region
    usage: /<command>
  rloc2:
    description: (MultiCraft) marks the second location in the selection of a region
    usage: /<command>
  rrbuild:
    description: (MultiCraft) builds a structure from rloc1 to rloc2 (Currently solid and made of stone)
    usage: /<command>
  eyebuild:
    description: (MultiCraft) build structure to gaze position
    usage: /<command> x(int) y(int) z(int) material(int)
  eyetrack:
    description: (MultiCraft) enable or disable eyetracking
    usage: /<command> mode(string)
  mstore:
    description: (MultiCraft) structure storage command
    usage: /<command> name(string)
  mclone:
    description: (MultiCraft) structure cloning command
    usage: /<command> name(string)
  copyloc1:
    description: (MultiCraft) marks the first location for the selection of a copy
    usage: /<command>
  copyloc2:
    description: (MultiCraft) marks the second location for the selection of a copy
    usage: /<command>
  mpaste:
    description: (MultiCraft) copies the region from copyloc1 to copyloc2 to cursor position
    usage: /<command>